image: yellow.hub.cambricon.com/magicmind/release/x86_64/magicmind:0.13.0-x86_64-ubuntu18.04-py_3_7

gen-jobs:
  stage: .pre
  tags: 
    - mlu370-s4
  script:
    - python ci/generate_config.py
  artifacts:
    paths:
      - jobs.yml
      - dist/*.whl

model-test:
  stage: test
  trigger:
    include:
      - artifact: jobs.yml
        job: gen-jobs
    strategy: depend
